### ISSUE TITLE
Consider pinning dev dependency versions

### ISSUE THREAD

**Issue by OR13** [erdtman/cwt-js#4]
```
  "devDependencies": {
    "ava": "*",
    "live-server": "*",
    "npm-run-all": "*",
    "nyc": "*",
    "semistandard": "*",
    "jsonfile": "*",
    "watch": "*"
  }
  ```
  
  I would guess these worked at one point with node6, but they don't work now...
  
  I am trying to find a node version that works with the latest....but an alternative would be to pin them to something that works in node6.

**Comment by erdtman** [comment]
fixed
